SCREEN_WIDTH = 1280 # px
SCREEN_HEIGHT = 720 # px
SCREEN_FPS = 60 # frames per second

ASTEROID_MIN_RADIUS = 20 # pxs
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS # px

PLAYER_RADIUS = 20 # px
PLAYER_TURN_SPEED = 300  # degrees per second
PLAYER_SPEED = 200  # px per second
PLAYER_SHOOT_COOLDOWN = 0.3 # seconds

PLAYER_SHOOT_SPEED = 500  # px per second
SHOT_RADIUS = 5 # px